apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-base:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpwd"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc